// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.2
// source: ns.proto

package ns

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSequenceNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSequenceNumRequest) Reset() {
	*x = GetSequenceNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ns_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSequenceNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSequenceNumRequest) ProtoMessage() {}

func (x *GetSequenceNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ns_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSequenceNumRequest.ProtoReflect.Descriptor instead.
func (*GetSequenceNumRequest) Descriptor() ([]byte, []int) {
	return file_ns_proto_rawDescGZIP(), []int{0}
}

type GetSequenceNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number uint32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *GetSequenceNumResponse) Reset() {
	*x = GetSequenceNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ns_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSequenceNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSequenceNumResponse) ProtoMessage() {}

func (x *GetSequenceNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ns_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSequenceNumResponse.ProtoReflect.Descriptor instead.
func (*GetSequenceNumResponse) Descriptor() ([]byte, []int) {
	return file_ns_proto_rawDescGZIP(), []int{1}
}

func (x *GetSequenceNumResponse) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type PutSequenceNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number uint32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *PutSequenceNumRequest) Reset() {
	*x = PutSequenceNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ns_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutSequenceNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSequenceNumRequest) ProtoMessage() {}

func (x *PutSequenceNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ns_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSequenceNumRequest.ProtoReflect.Descriptor instead.
func (*PutSequenceNumRequest) Descriptor() ([]byte, []int) {
	return file_ns_proto_rawDescGZIP(), []int{2}
}

func (x *PutSequenceNumRequest) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type PutSequenceNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PutSequenceNumResponse) Reset() {
	*x = PutSequenceNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ns_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutSequenceNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSequenceNumResponse) ProtoMessage() {}

func (x *PutSequenceNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ns_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSequenceNumResponse.ProtoReflect.Descriptor instead.
func (*PutSequenceNumResponse) Descriptor() ([]byte, []int) {
	return file_ns_proto_rawDescGZIP(), []int{3}
}

var File_ns_proto protoreflect.FileDescriptor

var file_ns_proto_rawDesc = []byte{
	0x0a, 0x08, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x6e, 0x73, 0x22, 0x17,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x30, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2f, 0x0a, 0x15, 0x50, 0x75, 0x74,
	0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x18, 0x0a, 0x16, 0x50, 0x75,
	0x74, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa4, 0x01, 0x0a, 0x0c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x19, 0x2e, 0x6e, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6e, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x49, 0x0a, 0x0e, 0x50, 0x75, 0x74, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e,
	0x75, 0x6d, 0x12, 0x19, 0x2e, 0x6e, 0x73, 0x2e, 0x50, 0x75, 0x74, 0x53, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x6e, 0x73, 0x2e, 0x50, 0x75, 0x74, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x18, 0x5a, 0x16, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x6e, 0x73, 0x3b, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ns_proto_rawDescOnce sync.Once
	file_ns_proto_rawDescData = file_ns_proto_rawDesc
)

func file_ns_proto_rawDescGZIP() []byte {
	file_ns_proto_rawDescOnce.Do(func() {
		file_ns_proto_rawDescData = protoimpl.X.CompressGZIP(file_ns_proto_rawDescData)
	})
	return file_ns_proto_rawDescData
}

var file_ns_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ns_proto_goTypes = []interface{}{
	(*GetSequenceNumRequest)(nil),  // 0: ns.GetSequenceNumRequest
	(*GetSequenceNumResponse)(nil), // 1: ns.GetSequenceNumResponse
	(*PutSequenceNumRequest)(nil),  // 2: ns.PutSequenceNumRequest
	(*PutSequenceNumResponse)(nil), // 3: ns.PutSequenceNumResponse
}
var file_ns_proto_depIdxs = []int32{
	0, // 0: ns.NumberServer.GetSequenceNum:input_type -> ns.GetSequenceNumRequest
	2, // 1: ns.NumberServer.PutSequenceNum:input_type -> ns.PutSequenceNumRequest
	1, // 2: ns.NumberServer.GetSequenceNum:output_type -> ns.GetSequenceNumResponse
	3, // 3: ns.NumberServer.PutSequenceNum:output_type -> ns.PutSequenceNumResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ns_proto_init() }
func file_ns_proto_init() {
	if File_ns_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ns_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSequenceNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ns_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSequenceNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ns_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutSequenceNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ns_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutSequenceNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ns_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ns_proto_goTypes,
		DependencyIndexes: file_ns_proto_depIdxs,
		MessageInfos:      file_ns_proto_msgTypes,
	}.Build()
	File_ns_proto = out.File
	file_ns_proto_rawDesc = nil
	file_ns_proto_goTypes = nil
	file_ns_proto_depIdxs = nil
}
